#!/usr/bin/env python
# encoding: utf-8
'''
src.SendCommand -- shortdesc

src.SendCommand is a description

It defines classes_and_methods

@author:     Norad Sparta

@copyright:  2014 organization_name. All rights reserved.

@license:    license

@contact:    norad.sparta@gmail.com
@deffield    updated: Updated
'''

import sys
import os
import pozo_term

from optparse import OptionParser

__all__ = []
__version__ = 0.1
__date__ = '2014-06-05'
__updated__ = '2014-06-05'

DEBUG = 1
TESTRUN = 0
PROFILE = 0

def main(argv=None):
    '''Command line options.'''

    program_name = os.path.basename(sys.argv[0])
    program_version = "v0.1"
    program_build_date = "%s" % __updated__

    program_version_string = '%%prog %s (%s)' % (program_version, program_build_date)
    #program_usage = '''usage: spam two eggs''' # optional - will be autogenerated by optparse
    program_longdesc = '''''' # optional - give further explanation about what the program does
    program_license = "Copyright 2014 Norad Sparta (codomatic)                                            \
                Licensed under the Apache License 2.0\nhttp://www.apache.org/licenses/LICENSE-2.0"

    if argv is None:
        argv = sys.argv[1:]
        print("is None ")
    try:
        print("try")
        # setup option parser
        parser = OptionParser(version=program_version_string, epilog=program_longdesc, description=program_license)
        parser.add_option("-i", "--in", dest="infile", help="set input path [default: %default]", metavar="FILE")
        parser.add_option("-o", "--out", dest="outfile", help="set output path [default: %default]", metavar="FILE")
        parser.add_option("-v", "--verbose", dest="verbose", action="count", help="set verbosity level [default: %default]")
        #parser.add_option("-a", "--address", dest="address", action="address", help="set ip address of a server [default: %default]")
        #parser.add_option("-p", "--port", dest="port", action="port", help="set port of a server [default: %default]")

        print("before2")

        # set defaults
        parser.set_defaults(outfile="./out.txt", infile="./in.txt")
        print("before3")
        
        # process options
        (opts, args) = parser.parse_args(argv)
        
        print("before4")
        if opts.verbose > 0:
            print("verbosity level = %d" % opts.verbose)
        if opts.infile:
            print("infile = %s" % opts.infile)
        if opts.outfile:
            print("outfile = %s" % opts.outfile)
        
        # MAIN BODY #
        
        #s = open_connection()
        s = 2
 
        print("HELLO ")
        while (True):
            user_input = raw_input("pozo> ")
            if ("quit" in user_input):
                print('bye!')
                break;
            elif ("pozocodes" in user_input):
                pozo_term.print_pozocode_h()
            elif ("ping" in user_input):
                print(pozo_term.pozo_ping(s))
            else:
                print ("pozo>?")
    

    except Exception, e:
        print("WWW exception")
        indent = len(program_name) * " "
        sys.stderr.write(program_name + ": " + repr(e) + "\n")
        sys.stderr.write(indent + "  for help use --help")
        return 2


if __name__ == "__main__":
    if DEBUG:
        sys.argv.append("-h")
    if TESTRUN:
        import doctest
        doctest.testmod()
    if PROFILE:
        import cProfile
        import pstats
        profile_filename = 'src.SendCommand_profile.txt'
        cProfile.run('main()', profile_filename)
        statsfile = open("profile_stats.txt", "wb")
        p = pstats.Stats(profile_filename, stream=statsfile)
        stats = p.strip_dirs().sort_stats('cumulative')
        stats.print_stats()
        statsfile.close()
        sys.exit(0)
    print ("before main")
    sys.exit(main())
    
    